language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0

before_install:
  - gem update bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.1.6"'
  - 'TEST_RAILS_VERSION="~> 5.2.3"'
  - 'TEST_RAILS_VERSION="~> 6.0.0"'
