language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.5

before_install:
  - gem update --system
  - gem install bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.0.7"'
  - 'TEST_RAILS_VERSION="~> 5.1.6"'
  - 'TEST_RAILS_VERSION="~> 5.2.3"'